services:

  actinia-cloudevent:
    build:
      context: ..
      dockerfile: docker/actinia-cloudevent-plugin-dev/Dockerfile
    volumes:
      - ..:/src/actinia-cloudevent-plugin/.
    cap_add:
      - SYS_PTRACE
    ports:
      - "5000:5000"
    network_mode: "host"

