FROM alpine:3.21

# python3 + pip3
RUN apk update; \
    apk add --no-cache python3 python3-dev
ENV PATH="/opt/venv/bin:$PATH"
RUN /usr/bin/python -m venv --system-site-packages --without-pip /opt/venv
RUN python -m ensurepip && pip3 install --upgrade pip pep517 wheel

# RUN pip3 install --no-cache-dir pwgen==0.8.2.post0

# COPY docker/actinia.cfg /etc/default/actinia
COPY . /src/actinia-cloudevent-plugin/

COPY docker/gunicorn.cfg /gunicorn.cfg

# SETUPTOOLS_SCM_PRETEND_VERSION is only needed if in the plugin folder is no
# .git folder
ENV SETUPTOOLS_SCM_PRETEND_VERSION=0.0

WORKDIR /src/actinia-cloudevent-plugin
RUN pip3 install --no-cache-dir -e .

# RUN python3 -m actinia_cloudevent_plugin.main
