---

name: actinia tests

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

  unittests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Replace run only unittest command
      run: |
        sed -i "s+# RUN make test+RUN make unittest+g" docker/Dockerfile
    - name: Unittests of actinia-cloudevent-plugin
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: actinia-cloudevent-plugin-tests:alpine
        context: .
        file: docker/Dockerfile
        no-cache: true
        # pull: true

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # with:
      #   path: "."
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Replace run integration test command
      run: |
        sed -i "s+# RUN make test+RUN make integrationtest+g" docker/Dockerfile
    - name: Integration tests of actinia-cloudevent-plugin
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: actinia-cloudevent-plugin-test:alpine
        context: .
        file: docker/Dockerfile
        no-cache: true
        # pull: true
