---

name: actinia tests

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

  # unittests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #   - name: Replace run only unittest command
  #     run: |
  #       sed -i "s+# RUN make test+RUN make unittest+g" docker/Dockerfile
  #   - name: Unittests of actinia-cloudevent-plugin
  #     id: docker_build
  #     uses: docker/build-push-action@v6
  #     with:
  #       push: false
  #       tags: actinia-cloudevent-plugin-tests:alpine
  #       context: .
  #       file: docker/Dockerfile
  #       no-cache: true
  #       # pull: true

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start containers
      run: docker compose -f "docker/docker-compose.yml" up -d --build
    - name: List running docker
      run: docker ps
    - name: Docker logs actinia-cloudevent
      run: docker logs docker-actinia-cloudevent-1
    - name: Docker logs actinia-core
      run: docker logs docker-actinia-core-1
    - name: Run integration test
      run: docker exec -t docker-actinia-cloudevent-1 make integrationtest
    - name: Stop containers
      run: docker compose -f "docker/docker-compose.yml" down
